wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1659268462
    t:
      1:
      - 55
      2:
      - 55
      4: 3.9.13
      5: 0.12.17
      8:
      - 5
