wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659362806
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
features:
  desc: null
  value:
    categorical:
    - time_signature
    - key
    nlp:
    - text_feature
    numerical:
    - danceability
    - energy
    - loudness
    - speechiness
    - acousticness
    - instrumentalness
    - liveness
    - valence
    - tempo
    - duration_ms
random_forest:
  desc: null
  value:
    bootstrap: true
    ccp_alpha: 0.0
    class_weight: balanced
    criterion: gini
    max_depth: 40
    max_features: auto
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_impurity_split: null
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 100
    n_jobs: null
    oob_score: false
    random_state: null
    verbose: 0
    warm_start: false
tfidf:
  desc: null
  value:
    max_features: 150
